apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boundary.worker.fullname" . }}
  labels:
    {{- include "boundary.worker.labels" . | nindent 4 }}
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "boundary.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boundary.worker.selectorLabels" . | nindent 8 }}
      {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "boundary.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      {{- with .Values.worker.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "bin/sh"
            - "-c"
          args:
            - "boundary server -config /boundary/boundary.hcl"
          volumeMounts:
            - mountPath: /boundary
              name: {{ template "boundary.worker.fullname" . }}
              readOnly: true
          resources:
            {{- .Values.worker.resources | toYaml | trim | nindent 12 }}
      volumes:
        - name: {{ template "boundary.worker.fullname" . }}
          configMap:
            name: {{ template "boundary.worker.fullname" . }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}