apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boundary.controller.fullname" . }}
  labels:
    {{- include "boundary.controller.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.controller.config }}
  {{ $key }}: |-
{{ tpl $val $| indent 4 }}
{{- end }}