apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boundary.controller.fullname" . }}
  labels:
    {{- include "boundary.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "boundary.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boundary.controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "boundary.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      {{- with .Values.controller.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.controller.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - "bin/sh"
            - "-c"
          args:
            - "boundary database migrate -config /boundary/boundary.hcl || boundary database init -config /boundary/boundary.hcl"
          volumeMounts:
            - mountPath: /boundary
              name: {{ template "boundary.controller.fullname" . }}
              readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.controller.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - "bin/sh"
            - "-c"
          args:
            - "boundary server -config /boundary/boundary.hcl"
          ports:
            - name: api
              containerPort: 9200
              protocol: TCP
            - name: cluster
              containerPort: 9201
              protocol: TCP
            - name: data
              containerPort: 9202
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.controller.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controller.readinessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /boundary
              name: {{ template "boundary.controller.fullname" . }}
              readOnly: true
          resources:
            {{- .Values.controller.resources | toYaml | trim | nindent 12 }}
      volumes:
        - name: {{ template "boundary.controller.fullname" . }}
          configMap:
            name: {{ template "boundary.controller.fullname" . }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}