apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.fullname" . }}
  labels:
    {{- include "boundary.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{ . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: 9201
      targetPort: cluster
      protocol: TCP
      name: cluster
    - port: 9202
      targetPort: data
      protocol: TCP
      name: data
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}