apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ tpl $val $| indent 4 }}
{{- end }}