apiVersion: v1
kind: Service
metadata:
  name: {{ include "steampipe.fullname" . }}
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: bbdd
      protocol: TCP
      name: bbdd
  selector:
    {{- include "steampipe.selectorLabels" . | nindent 4 }}